import { createDefaultSlot, type TimeSlot } from "./expertAvailability";
import type { ExpertApplicationSubmission } from "./expertApplicationSubmission";

function createDemoDefaultSlot(): TimeSlot {
  return {
    ...createDefaultSlot(),
    days: ["Mon", "Tue", "Wed", "Thu", "Fri"],
  };
}

export const DEMO_APPLICATION_APP_IDS = [
  "APP-1079",
  "APP-1080",
  "APP-1081",
  "APP-1082",
  "APP-1083",
] as const;

function hoursAgo(hours: number): string {
  return new Date(Date.now() - hours * 60 * 60 * 1000).toISOString();
}

const demoEmployment = [
  {
    id: "emp-1",
    jobTitle: "Senior Legal Consultant",
    company: "Independent Practice",
    startMonth: "03",
    startYear: "2018",
    endMonth: "",
    endYear: "",
    currentlyWorking: true,
    responsibilities:
      "Advised startup founders on incorporation, ESOP plans, and commercial contracts.",
  },
];

const demoEducation = [
  {
    id: "edu-1",
    degree: "LLB",
    fieldOfStudy: "Corporate Law",
    institution: "National Law School of India University",
    graduationYear: "2014",
    honours: "First Class",
  },
];

function demoDefaults(
  overrides: Partial<ExpertApplicationSubmission>,
): ExpertApplicationSubmission {
  const submittedAt = overrides.submittedAt ?? hoursAgo(24);
  return {
    employmentPositions: demoEmployment,
    educationDegrees: demoEducation,
    acceptCustomRequests: false,
    termsAcceptedAt: submittedAt,
    portfolioLinks: [],
    portfolioSamples: [],
    ...overrides,
  } as ExpertApplicationSubmission;
}

export function getDemoExpertApplications(): ExpertApplicationSubmission[] {
  return [
    demoDefaults({
      appId: "APP-1079",
      submittedAt: hoursAgo(38),
      status: "in_review",
      name: "Arjun Mehta",
      email: "arjun.mehta@example.com",
      phone: "+91 98765 43210",
      categoryId: "legal",
      categoryLabel: "Legal & Compliance",
      skills: ["Corporate Law", "Startup Legal", "Contract Drafting", "ESOP Structuring"],
      experienceLevel: "leader",
      professionalTitle: "Senior Legal Consultant",
      tagLine: "Practical legal advice for founders, in plain language.",
      bio: "Corporate and commercial law specialist advising startups and SMEs across India. Former in-house counsel at a Series B fintech.",
      avatar: "/assets/img/avatar2.png",
      location: "Bangalore, Karnataka",
      linkedin: "linkedin.com/in/arjun-mehta-legal",
      portfolio: "arjunmehta.legal",
      portfolioLinks: [
        { id: "portfolio-linkedin", url: "linkedin.com/in/arjun-mehta-legal", platform: "LinkedIn" },
        { id: "portfolio-site", url: "arjunmehta.legal", platform: "Portfolio" },
      ],
      certificates: [
        { id: "d1", name: "Bar Council Certificate.pdf", size: "2.1 MB" },
        { id: "d2", name: "Government Photo ID.pdf", size: "1.0 MB" },
        { id: "d3", name: "LLB Degree Certificate.pdf", size: "3.2 MB" },
      ],
      formats: ["video", "written"],
      lengths: ["30", "45"],
      formatPrices: { video: "1200", written: "299" },
      languages: ["English", "Hindi", "Kannada"],
      audiences: ["startup", "smb"],
      timezone: "Asia/Kolkata",
      availabilitySlots: [createDemoDefaultSlot()],
    }),
    demoDefaults({
      appId: "APP-1080",
      submittedAt: hoursAgo(14),
      status: "pending",
      name: "Priya Sharma",
      email: "priya.sharma@example.com",
      phone: "+91 91234 56780",
      categoryId: "design",
      categoryLabel: "Product Design",
      skills: ["UI / UX Design", "Design Systems", "User Research", "Prototyping"],
      experienceLevel: "established",
      professionalTitle: "Lead Product Designer",
      tagLine: "Design clarity for early-stage product teams.",
      bio: "Product designer with 6 years across B2B SaaS and consumer apps. I help teams ship usable v1s fast.",
      avatar: "/assets/img/avatar3.png",
      location: "Mumbai, Maharashtra",
      linkedin: "linkedin.com/in/priya-sharma-ux",
      portfolio: "priyasharma.design",
      portfolioLinks: [
        { id: "portfolio-linkedin", url: "linkedin.com/in/priya-sharma-ux", platform: "LinkedIn" },
        { id: "portfolio-site", url: "priyasharma.design", platform: "Portfolio" },
      ],
      employmentPositions: [
        {
          id: "emp-1",
          jobTitle: "Lead Product Designer",
          company: "Northstar SaaS",
          startMonth: "01",
          startYear: "2020",
          endMonth: "",
          endYear: "",
          currentlyWorking: true,
          responsibilities: "Led design systems and onboarding flows for a B2B analytics platform.",
        },
      ],
      educationDegrees: [
        {
          id: "edu-1",
          degree: "Bachelor's Degree",
          fieldOfStudy: "Interaction Design",
          institution: "MIT Institute of Design",
          graduationYear: "2018",
          honours: "",
        },
      ],
      certificates: [{ id: "d1", name: "Google UX Certificate.pdf", size: "1.8 MB" }],
      formats: ["written", "audio"],
      lengths: ["30"],
      formatPrices: { written: "399", audio: "699" },
      languages: ["English", "Hindi"],
      audiences: ["startup", "career"],
      timezone: "Asia/Kolkata",
      availabilitySlots: [createDemoDefaultSlot()],
    }),
    demoDefaults({
      appId: "APP-1081",
      submittedAt: hoursAgo(54),
      status: "pending",
      name: "Amit Patel",
      email: "amit.patel@example.com",
      phone: "+91 99887 76655",
      categoryId: "marketing",
      categoryLabel: "Marketing & Growth",
      skills: ["SEO Strategy", "Content Marketing"],
      experienceLevel: "emerging",
      professionalTitle: "Growth Marketer",
      tagLine: "",
      bio: "",
      avatar: "/assets/img/avatar4.png",
      location: "Ahmedabad, Gujarat",
      linkedin: "",
      portfolio: "",
      employmentPositions: [],
      educationDegrees: [],
      certificates: [],
      formats: ["written"],
      lengths: ["15"],
      formatPrices: { written: "199" },
      languages: ["English", "Gujarati"],
      audiences: ["smb"],
      timezone: "Asia/Kolkata",
      availabilitySlots: [],
    }),
    demoDefaults({
      appId: "APP-1082",
      submittedAt: hoursAgo(28),
      status: "on_hold",
      name: "Neha Kapoor",
      email: "neha.kapoor@example.com",
      phone: "+91 98100 22334",
      categoryId: "finance",
      categoryLabel: "Finance & VC",
      skills: ["VC Fundraising", "Financial Modeling", "Cap Tables", "Pitch Deck Review"],
      experienceLevel: "established",
      professionalTitle: "Startup Finance Advisor",
      tagLine: "Fundraising prep for seed to Series A founders.",
      bio: "Former VC associate supporting 40+ founder conversations on metrics, narrative, and term sheets.",
      avatar: "/assets/img/avatar1.png",
      location: "Delhi NCR",
      linkedin: "linkedin.com/in/neha-kapoor-finance",
      portfolio: "",
      employmentPositions: [
        {
          id: "emp-1",
          jobTitle: "Associate",
          company: "Horizon Ventures",
          startMonth: "06",
          startYear: "2019",
          endMonth: "12",
          endYear: "2023",
          currentlyWorking: false,
          responsibilities: "Evaluated seed and Series A deals across fintech and SaaS.",
        },
      ],
      educationDegrees: [
        {
          id: "edu-1",
          degree: "MBA",
          fieldOfStudy: "Finance",
          institution: "ISB Hyderabad",
          graduationYear: "2019",
          honours: "",
        },
      ],
      certificates: [{ id: "d1", name: "CFA Level II Certificate.pdf", size: "2.0 MB" }],
      formats: ["video", "written"],
      lengths: ["30", "60"],
      formatPrices: { video: "1500", written: "499" },
      languages: ["English", "Hindi"],
      audiences: ["startup", "enterprise"],
      timezone: "Asia/Kolkata",
      availabilitySlots: [createDemoDefaultSlot()],
      reviewerNote: "On hold — waiting for updated portfolio link and intro video upload.",
    }),
    demoDefaults({
      appId: "APP-1083",
      submittedAt: hoursAgo(8),
      status: "in_review",
      name: "Rohan Desai",
      email: "rohan.desai@example.com",
      phone: "+91 90909 80808",
      categoryId: "software",
      categoryLabel: "Software Engineering",
      skills: [
        "Backend Architecture",
        "System Design",
        "Cloud & DevOps",
        "API Integrations",
        "Database Tuning",
      ],
      experienceLevel: "leader",
      professionalTitle: "Principal Software Engineer",
      tagLine: "Scalable systems for high-growth engineering teams.",
      bio: "Engineering leader with 11 years building payment and marketplace platforms. Mentoring staff engineers on architecture reviews.",
      avatar: "/assets/img/manportrait.png",
      location: "Pune, Maharashtra",
      linkedin: "linkedin.com/in/rohan-desai-eng",
      portfolio: "rohandesai.dev",
      portfolioLinks: [
        { id: "portfolio-linkedin", url: "linkedin.com/in/rohan-desai-eng", platform: "LinkedIn" },
        { id: "portfolio-site", url: "rohandesai.dev", platform: "Portfolio" },
      ],
      employmentPositions: [
        {
          id: "emp-1",
          jobTitle: "Principal Engineer",
          company: "PayGrid",
          startMonth: "02",
          startYear: "2019",
          endMonth: "",
          endYear: "",
          currentlyWorking: true,
          responsibilities: "Owns platform architecture for payments and ledger services.",
        },
      ],
      educationDegrees: [
        {
          id: "edu-1",
          degree: "Bachelor's Degree",
          fieldOfStudy: "Computer Science",
          institution: "COEP Technological University",
          graduationYear: "2013",
          honours: "",
        },
      ],
      certificates: [
        { id: "d1", name: "AWS Solutions Architect.pdf", size: "1.4 MB" },
        { id: "d2", name: "Identity Document.pdf", size: "0.9 MB" },
      ],
      formats: ["video", "written", "group"],
      lengths: ["45", "60"],
      formatPrices: { video: "1800", written: "349", group: "2499" },
      languages: ["English", "Marathi"],
      audiences: ["startup", "enterprise", "career"],
      timezone: "Asia/Kolkata",
      availabilitySlots: [createDemoDefaultSlot()],
      acceptCustomRequests: true,
    }),
  ];
}
