import type { RequestDetailModel } from "@/lib/expertRequestDetailStore";

const pdfSafe = (value: string) => value.replace(/₹\s?/g, "INR ").replace(/[–—]/g, "-");

export async function downloadRequestSummaryPdf(data: RequestDetailModel): Promise<void> {
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 18;
  const contentWidth = pageWidth - margin * 2;
  let y = 20;

  const ensureSpace = (height: number) => {
    if (y + height <= 278) return;
    doc.addPage();
    y = 20;
  };
  const row = (label: string, value: string) => {
    ensureSpace(9);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(95, 99, 104);
    doc.setFontSize(9);
    doc.text(label, margin, y);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(25, 28, 32);
    doc.text(pdfSafe(value || "Not provided"), pageWidth - margin, y, { align: "right", maxWidth: 105 });
    y += 8;
  };
  const heading = (title: string) => {
    ensureSpace(15);
    y += 4;
    doc.setFillColor(244, 246, 248);
    doc.roundedRect(margin, y - 6, contentWidth, 10, 2, 2, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(29, 40, 51);
    doc.text(title, margin + 4, y);
    y += 10;
  };

  doc.setFillColor(20, 43, 63);
  doc.rect(0, 0, pageWidth, 34, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text("JATAYU", margin, 16);
  doc.setFontSize(12);
  doc.text("Booking Request Summary", margin, 25);
  y = 44;

  row("Request ID", data.id);
  row("Status", data.statusText);
  row("Submitted", data.submittedDate);

  heading("Seeker");
  row("Name", data.client.name);
  row("Category", data.client.role);
  row("Location", data.client.location);
  row("Timezone", data.client.timezone);
  row("Languages", data.sessionDetails.language);

  heading("Request Details");
  row("Subject", data.title);
  row("Consultation Type", data.sessionDetails.format);
  row("Scheduled For", data.sessionDetails.requestedDate);
  row("Time and Duration", data.sessionDetails.duration);
  row("Participants", data.sessionDetails.participantsCount);
  if (data.proposal.tags.length) row("Topics", data.proposal.tags.join(", "));

  ensureSpace(25);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(95, 99, 104);
  doc.text("Context", margin, y);
  y += 5;
  doc.setFont("helvetica", "normal");
  doc.setTextColor(25, 28, 32);
  const contextLines = doc.splitTextToSize(pdfSafe(data.proposal.summary || "No additional context provided."), contentWidth);
  for (const line of contextLines) {
    ensureSpace(6);
    doc.text(line, margin, y);
    y += 5;
  }

  heading("Payment Summary");
  row("Payment Status", data.paymentStatus);
  row("Consultation Fee", data.paymentDetails?.consultationFee || data.sessionDetails.proposedPrice);
  if (data.paymentDetails) {
    row("Platform Fee", data.paymentDetails.platformFee);
    row("GST", data.paymentDetails.gst);
    row("Credits Applied", data.paymentDetails.creditsApplied);
    row("Payable Amount", data.paymentDetails.payable);
  }

  const pages = doc.getNumberOfPages();
  for (let page = 1; page <= pages; page += 1) {
    doc.setPage(page);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(120, 124, 128);
    doc.text(`Generated by Jatayu | Page ${page} of ${pages}`, pageWidth / 2, 290, { align: "center" });
  }

  const safeId = data.id.replace(/[^a-zA-Z0-9_-]/g, "-");
  doc.save(`jatayu-request-${safeId}.pdf`);
}
